include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_put_required_named_parameters_first
    - lines_longer_than_80_chars
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
