name: flutter_bizpage
description: Flutter BizPage
publish_to: none
version: 0.0.10

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"

dependencies:
  device_info_plus: ^4.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  package_info_plus: ^1.4.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.2

flutter:
  assets:
    - google_fonts/
    - images/

  uses-material-design: true
