name: flutter_bizpage
description: Flutter BizPage
publish_to: none
version: 0.0.9

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  device_info_plus: ^4.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  assets:
    - google_fonts/
    - images/

  uses-material-design: true
