name: flutter_bizpage
description: Flutter BizPage
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^2.1.0
  flutter_riverpod: ^0.14.0+3
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - google_fonts/
    - images/

  uses-material-design: true
