name: flutter_bizpage
description: Flutter BizPage
version: 0.0.2

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^3.1.0
  flutter_riverpod: ^0.14.0+3
  url_launcher: ^6.0.12
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - google_fonts/
    - images/

  uses-material-design: true
