name: flutter_bizpage
description: Flutter BizPage
publish_to: none
version: 0.0.11

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0
  device_info_plus: ^11.5.0
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^9.0.0

flutter:
  assets:
    - google_fonts/
    - images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: google_fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: google_fonts/OpenSans-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Regular.ttf

  uses-material-design: true
