name: flutter_bizpage
description: Flutter BizPage
publish_to: none
version: 0.0.8

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^3.2.2
  flutter_riverpod: ^1.0.3
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.0

dev_dependencies:
  akaiser_flutter_lints:
    git: https://github.com/akaiser/akaiser_flutter_lints.git
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - google_fonts/
    - images/

  uses-material-design: true
