name: Setup Flutter
description: "What the name says..."

runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.32.5
        channel: stable
        cache: true
