name: Release Web
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-flutter
      - name: Build
        run: flutter build web --base-href /flutter_bizpage/
      - name: Upload
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
