name: Release Android
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-flutter
      - name: Build
        run: flutter build apk --split-per-abi --release
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
