name: Release Desktop
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release-desktop:
    strategy:
      matrix:
        include:
          #- platform: linux
          #  runs-on: ubuntu-latest
          #  build-dir: build/linux/x64/release/bundle
          - platform: macos
            runs-on: macos-latest
            build-dir: build/macos/Build/Products/Release
          #- platform: windows
          #  runs-on: windows-latest
          #  build-dir: build/windows/runner/Release
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-flutter
      - name: Build
        run: flutter build ${{ matrix.platform }}
      - name: Zip
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: desktop-${{github.ref_name}}-${{ matrix.platform }}-x64.zip
          directory: ${{ matrix.build-dir }}
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ matrix.build-dir }}/desktop-${{github.ref_name}}-${{ matrix.platform }}-x64.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
